; generated by Component: ARM Compiler 5.06 update 6 (build 750) Tool: ArmCC [4d3637]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o.\output\nrf_delay.s --depend=.\output\nrf_delay.d --cpu=Cortex-M4.fp.sp --apcs=interwork -O0 --diag_suppress=9931 -I.\APP -I.\BLE\ble_advertising -I.\BLE\ble_services\ble_dis -I.\BLE\ble_services\ble_nus -I.\BLE\common -I.\Doc -I.\Drivers\bsp -I.\Drivers\common -I.\Drivers\config -I.\Drivers\delay -I.\Drivers\flash -I.\Drivers\hal -I.\Drivers\ppi -I.\Drivers\pstorage\config -I.\Drivers\pstorage -I.\Drivers\RTE -I.\Drivers\saadc -I.\Drivers\segger_rtt -I.\Drivers\timer -I.\Drivers\uart -I.\Libraries\fifo -I.\Libraries\fstorage -I.\Libraries\gpiote -I.\Libraries\pwm -I.\Libraries\timer -I.\Libraries\uart -I.\Libraries\util -I.\RTE\Device\nRF52832_xxAA -I.\softdevice\common\softdevice_handler -I.\softdevice\s132\headers -I.\Libraries\experimental_section_vars -I.\Libraries\fstorage\config -I.\Drivers\bsp -I.\Drivers\Bluetooth -I.\Drivers\simuart -I.\Drivers\wifi -I.\Drivers\wdt -I.\RSA -I.\RTE\_WIFI -IC:\Users\Administrator\AppData\Local\Arm\Packs\ARM\CMSIS\5.6.0\CMSIS\Core\Include -IC:\Users\Administrator\AppData\Local\Arm\Packs\NordicSemiconductor\nRF_DeviceFamilyPack\8.5.0\Device\Include -D__MICROLIB -D__UVISION_VERSION=529 -D_RTE_ -DNRF52 -DBLE_STACK_SUPPORT_REQD -DBOARD_PCA10040 -DNRF52_PAN_12 -DNRF52_PAN_15 -DNRF52_PAN_20 -DNRF52_PAN_30 -DNRF52_PAN_31 -DNRF52_PAN_36 -DNRF52_PAN_51 -DNRF52_PAN_53 -DNRF52_PAN_54 -DNRF52_PAN_55 -DNRF52_PAN_58 -DNRF52_PAN_62 -DNRF52_PAN_63 -DNRF52_PAN_64 -DS132 -DNRF_LOG_USES_UART=1 -DNRF52 -DSOFTDEVICE_PRESENT -DCONFIG_NFCT_PINS_AS_GPIOS -DSWI_DISABLE0 --omf_browse=.\output\nrf_delay.crf Drivers\delay\nrf_delay.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.nrf_delay_ms||, CODE, READONLY, ALIGN=1

nrf_delay_ms PROC
        PUSH     {r0,lr}
        B        |L0.18|
|L0.4|
        LDR      r0,[sp,#0]
        SUBS     r0,r0,#1
        STR      r0,[sp,#0]
        MOV      r0,#0x3e7
        BL       __asm___11_nrf_delay_c_532987f3__nrf_delay_us
|L0.18|
        LDR      r0,[sp,#0]
        CMP      r0,#0
        BNE      |L0.4|
        POP      {r3,pc}
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "Drivers\\delay\\nrf_delay.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___11_nrf_delay_c_532987f3____REV16|
#line 492 "C:\\Users\\Administrator\\AppData\\Local\\Arm\\Packs\\ARM\\CMSIS\\5.6.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___11_nrf_delay_c_532987f3____REV16| PROC
#line 493

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___11_nrf_delay_c_532987f3____REVSH|
#line 507
|__asm___11_nrf_delay_c_532987f3____REVSH| PROC
#line 508

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___11_nrf_delay_c_532987f3____RRX|
#line 694
|__asm___11_nrf_delay_c_532987f3____RRX| PROC
#line 695

 rrx r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE
	THUMB
	EXPORT |__asm___11_nrf_delay_c_532987f3__nrf_delay_us|
#line 16 "Drivers\\delay\\nrf_delay.h"
|__asm___11_nrf_delay_c_532987f3__nrf_delay_us| PROC
#line 17

loop
 SUBS R0, R0, #1
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP

 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP

 BNE loop
 BX LR
	ENDP

;*** End   embedded assembler ***

        EXPORT nrf_delay_ms [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
